### ISSUE TITLE
Run savage on cluster (fresh install from Bioconda repo)

### ISSUE THREAD

**Issue by jblamyatifremer** [HaploConduct/HaploConduct#2]
Hi Jasmijn,

We are able to install and run successfull savage from bitbucket repo without any problem on a local pc with ubuntu 18.04. However, due to larger need in term of RAM (haplotypes reconstruction on herpesvirus (200 kp + 2000 x of coverage)), we need to move our (big) cluster [datarmor in french](https://wwz.ifremer.fr/Recherche-Technologie/Infrastructures-de-recherche/Infrastructures-numeriques/Pole-de-Calcul-et-de-Donnees-pour-la-Mer) (CentOS). We are able to install savage but when we try to launch savage we get the following error :

`symbol lookup error: /home/datawor-hemovir/env-Hemovir-longReads/opt/savage-0.4.0/bin/ViralQuasispecies: undefined symbol: _ZN5boost15program_options3argE`

The boost libraires were installed in the conda env... see below in bold. We have no more idea to solve this.
##------------------------------------------------------------------------------------------------
packages in environment at /home/datawork-hemovir/env-Hemovir-longReads:

Name                    Version                   Build  Channel
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports_abc             0.5                        py_1    conda-forge
bcftools                  1.9                  h47928c2_2    bioconda
bedtools                  2.27.1               he860b03_3    bioconda
biopython                 1.68                     py27_0    bioconda
blas                      1.0                         mkl  
blosc                     1.15.0               hd408876_0  
# boost                     1.67.0                   py27_4  
# boost-cpp                 1.67.0               h14c3975_4  
bowtie2                   2.3.4.3          py27he860b03_1    bioconda
bwa                       0.7.17               h84994c4_5    bioconda
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py27_0  
curl                      7.63.0            hbc83047_1000  
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.6               h746ee38_0  
expat                     2.2.6                he6710b0_0  
fast5                     0.6.5                         1    bioconda
fastqc                    0.11.8                        1    bioconda
font-ttf-dejavu-sans-mono 2.37                 h6964260_0  
fontconfig                2.13.0               h9420a91_0  
freebayes                 1.3.1            py27h56106d0_0    bioconda
freetype                  2.9.1                h8a8886c_1  
functools32               3.2.3.2                  py27_1  
futures                   3.2.0                    py27_0  
glib                      2.56.2               hd408876_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py27h989c5e5_3  
hdf5                      1.10.2               hba1933b_1  
hmmer                     3.2.1                hf484d3e_1    bioconda
htslib                    1.9                  h47928c2_5    bioconda
icu                       58.2                 h9c2bf20_1  
intel-openmp              2019.1                      144  
jpeg                      9b                   h024ee3a_2  
kallisto                  0.44.0               h7d86c95_2    bioconda
kiwisolver                1.1.0            py27he6710b0_0  
krb5                      1.16.1               h173b8e3_7  
libboost                  1.67.0               h46d08c1_4  
libcurl                   7.63.0            h20c2e04_1000  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.36               hbc83047_0  
libssh2                   1.8.0                h1ba5d50_4  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
linecache2                1.0.0                      py_1    conda-forge
lzo                       2.10                 h49e0be7_2  
mafft                     7.407                hf484d3e_2    bioconda
matplotlib                2.2.3            py27hb69df0a_0  
minimap2                  2.16                 h84994c4_1    bioconda
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py27ha843d7b_0  
mkl_random                1.0.2            py27hd81dba3_0  
mmtf-python               1.1.2                      py_0    conda-forge
msgpack-python            0.6.1            py27hfd86e86_1  
nanopolish                0.4.0                         0    bioconda
ncurses                   6.1                  he6710b0_1  
numexpr                   2.6.9            py27h9e4a6bb_0  
numpy                     1.16.2           py27h7e9f1db_0  
numpy-base                1.16.2           py27hde5b4d6_0  
olefile                   0.46                       py_0    conda-forge
openjdk                   8.0.152              h46b5887_1  
openssl                   1.1.1c               h7b6447c_1  
pandas                    0.24.2           py27he6710b0_0  
parallel                  20160622                      1    bioconda
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.42                 h439df22_0  
pear                      0.9.6                h98de208_5    bioconda
perl                      5.26.2               h14c3975_0  
perl-threaded             5.22.0                       13    bioconda
picard                    2.18.14                       0    bioconda
pillow                    6.0.0            py27h34e0f95_0  
pip                       19.1.1                   py27_0  
py-boost                  1.67.0           py27h04863e7_4  
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py27h05f1152_2  
pysam                     0.15.2           py27h1671916_1    bioconda
pysamstats                1.1.2            py27h84994c4_4    bioconda
pytables                  3.4.4            py27ha205bf6_0  
python                    2.7.15               h9bab390_6  
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
qt                        5.9.7                h5867ecd_1  
racon                     1.3.2                he941832_0    bioconda
readline                  7.0                  h7b6447c_5  
reportlab                 3.5.23           py27he686d34_0  
rust-overlaps             0.1.1                h84994c4_4    bioconda
samtools                  1.9                  h91753b0_5    bioconda
savage                    0.4.0            py27h02d93b8_2    bioconda
scipy                     1.2.1            py27h7c811a0_0  
seaborn                   0.9.0                      py_0    conda-forge
seqkit                    0.10.1                        1    bioconda
setuptools                41.0.1                   py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.19.8           py27hf484d3e_0  
six                       1.12.0                   py27_0  
snappy                    1.1.7                hbae5bb6_3  
snpeff                    4.3.1t                        2    bioconda
snpsift                   4.3.1t                        1    bioconda
sqlite                    3.26.0               h7b6447c_0  
statsmodels               0.9.0            py27h035aef0_0  
subprocess32              3.5.4            py27h7b6447c_0  
tabix                     0.2.6                ha92aebf_0    bioconda
tbb                       2019.4               hfd86e86_0  
tk                        8.6.8                hbc83047_0  
tornado                   5.1.1            py27h7b6447c_0  
traceback2                1.4.0                    py27_0  
trimmomatic               0.38                          1    bioconda
unittest2                 1.1.0                    py27_0  
vcflib                    1.0.0_rc2            h56106d0_2    bioconda
vcftools                  0.1.16               he860b03_3    bioconda
vt                        2015.11.10           he941832_3    bioconda
wheel                     0.33.4                   py27_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

I am looking forward to read you on this specific problem...
JB

**Comment by jblamyatifremer** [comment]
Finally I found the solution... Some newbies foxes could be interested :

The conda env is crowed by several softwares that use the same (boost?) libraires that create conflits.  It is my hypothesis. Indeed when a conda env is build up from scratch without any additional soft (except those included in savage), It works !

**Comment by jbaaijens** [comment]
Hi @jblamyatifremer,

Good to see you already found a solution. I noticed that you've installed savage-0.4.0, I think that these boost-related issues should be fixed in version 0.4.1 (at this version the conda recipe was revised). If you experience any further problems please let me know!

Jasmijn
