### ISSUE TITLE
Kallisto not found

### ISSUE THREAD

**Issue by sposadac** [HaploConduct/HaploConduct#3]
Hi Jasmijn,

I have encountered an issue while using option `--outdir` and `kallisto`. When calling `kallisto quant`,  the working directory has been set to the `outdir`, but I specify  the path to the input `fastq` files relative to the directory in which the script is executed. As a result, the filtering step based on `kallisto` is skipped as it returns an error. 

A work around is to specify the absolute path to `input_p1`, `input_p2` and `input_s`, but one could also handle it in the script. 

Thanks, Susana

**Comment by maciejmotyka** [comment]
Confirmed.
```
$ savage --revcomp -t 8 -o ./ass2 --split 1 -p1 2_S4_R1_clean.fastq -p2 2_S4_R2_clean.fastq

--- Filtering contigs ---
Kallisto index construction... 
Kallisto abundance quantification... 

Kallisto not found - skipping this filtering step.
```
```
$ savage --revcomp -t 8 -o . --split 1 -p1 ../2_S4_R1_clean.fastq -p2 ../2_S4_R2_clean.fastq 

--- Filtering contigs ---
Kallisto index construction... 
Kallisto abundance quantification... 
Filtered contigs_stage_c.fasta down to 31 contigs.
```

**Comment by jbaaijens** [comment]
Hi Susana,

Thanks for pointing this out, I will handle this asap!

Jasmijn

**Comment by jbaaijens** [comment]
This problem should be fixed with the above commit. Please reopen if any issues persist!
