### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by mhopken** [HaploConduct/HaploConduct#4]
Hello,

I am getting a Python error when trying to run SAVAGE.
Any help would be greatly appreciated.

Command used:
/home/matt_hopken/.conda/envs/py2/opt/savage-0.4.1/savage.py --ref AH0119559_S_HA.fasta --split 3 -m 100 -s AH0119559S_S59_L001_R1_001_unpaired.fastq -p1 AH0119559S_S59_L001_R1_001_paired.fastq -p2 AH0119559S_S59_L001_R2_001_paired.fastq

Parameter values:
filtering = True
reference = AH0119559_S_HA.fasta
merge_contigs = 0.0
remove_branches = True
contig_len_stage_c = 100
split_num = 3
use_subreads = True
no_assembly = False
diploid_contig_len = 200
overlap_stage_c = 100
input_p2 = AH0119559S_S59_L001_R2_001_paired.fastq
input_p1 = AH0119559S_S59_L001_R1_001_paired.fastq
count_strains = False
min_clique_size = 4
diploid_overlap_len = 30
compute_overlaps = True
preprocessing = True
threads = 1
stage_a = True
stage_b = True
stage_c = True
max_tip_len = None
min_overlap_len = 100
outdir = None
average_read_len = None
sfo_mm = 50
revcomp = False
input_s = AH0119559S_S59_L001_R1_001_unpaired.fastq
diploid = False

Input fastq stats:
Number of single-end reads = 112408
Number of paired-end reads = 259622
Total number of bases = 50555683
Average sequence length = 135.9

Using max_tip_len = 136
*******************
Preprocessing input
Traceback (most recent call last):
  File "/home/matt_hopken/.conda/envs/py2/opt/savage-0.4.1/savage.py", line 816, in <module>
    sys.exit(main())
  File "/home/matt_hopken/.conda/envs/py2/opt/savage-0.4.1/savage.py", line 287, in main
    overwrite_dir(args.outdir + '/stage_a')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by maciejmotyka** [comment]
You have to specify the output directory. I recommend creating a folder for each assembly and calling savage from inside that folder with "-o ." argument. If you use "-o /some/other/directory" filtering step with Kallisto will not be performed due to another bug #3 .

**Comment by jbaaijens** [comment]
As suggested above, please specify an output directory ("-o ." for current). This bug has been fixed in the source code but not yet in the conda version, sorry. Hope to take care of this soon!

**Comment by mhopken** [comment]
Thank you both! I will give it a try.

**Comment by jbaaijens** [comment]
This should be fixed with SAVAGE version 0.4.2, now also available on Bioconda!
