### ISSUE TITLE
Is HaploConduct suitable for large and high heterozygous rate plant genome?

### ISSUE THREAD

**Issue by xiekunwhy** [HaploConduct/HaploConduct#6]
Hi @jbaaijens 

I am looking for some assemblers to assemble a high heterozygous rate plant genome(diploid, het rate > 2%, haplotype genome size ~3.6G).
I have a computer with 20 cores and 500Gb RAM. Could I use HaploConduct to assemble (de novo assemble) such a genome on this computer(~90X illumina PE 150 data there)?

Best wishes,
Kun

**Comment by jbaaijens** [comment]
Hi Kun,

I'm afraid HaploConduct can't handle full plant genomes. POLYTE can assemble highly heterozygous regions for diploids, but currently it does not scale well beyond several megabases so you would have to be extremely patient ;)

Best,
Jasmijn
